USE madb_n;
SELECT DISTINCT e.JOB AS 職務, e.ENAME AS 僱員, MIN(e.SAL) AS 最低薪 FROM emp AS e
INNER JOIN 
	(SELECT JOB, MIN(SAL) AS MIN_LOW FROM emp GROUP BY JOB) AS LOW
	ON e.JOB = LOW.JOB AND e.SAL = LOW.MIN_LOW
GROUP BY e.JOB, e.ENAME ORDER BY e.SAL ASC